"""Atomic copy into a NEW, isolated PostgreSQL rehearsal schema.

This is deliberately a data-preservation stage. It must never be selected as a
runtime backend until the recorded application blockers have been resolved.
"""
from contextlib import closing
from datetime import datetime, timezone
import json
import re

from . import PILOT_FORMAT
from .source import TYPES, content_digest, inventory, quote, readonly


def schema_name(value):
    if not isinstance(value, str) or not re.fullmatch(r'turto_pilot_[a-z0-9_]{1,40}', value):
        raise ValueError('Schéma musí mít název turto_pilot_ a 1 až 40 malých písmen, číslic či podtržítek.')
    return value


def _qualified(schema, table):
    from psycopg import sql
    return sql.Identifier(schema, table)


def _table_sql(schema, table):
    from psycopg import sql
    definitions = []
    for column in table['columns']:
        identity = column['name'] == table['identity']
        definitions.append(sql.SQL('{} {}{}{}').format(
            sql.Identifier(column['name']), sql.SQL(TYPES[column['type'].upper()]),
            sql.SQL(' GENERATED BY DEFAULT AS IDENTITY' if identity else ''),
            sql.SQL(' NOT NULL' if column['notnull'] or column['pk'] else '')))
    primary = [c['name'] for c in sorted(table['columns'], key=lambda c: c['pk']) if c['pk']]
    if primary:
        definitions.append(sql.SQL('PRIMARY KEY ({})').format(sql.SQL(',').join(map(sql.Identifier, primary))))
    for index in table['unique']:
        if not index['partial'] and all(term[1] >= 0 for term in index['terms']):
            definitions.append(sql.SQL('UNIQUE ({})').format(
                sql.SQL(',').join(sql.Identifier(term[2]) for term in index['terms'])))
    return sql.SQL('CREATE TABLE {} ({})').format(_qualified(schema, table['name']), sql.SQL(',').join(definitions))


def _foreign_keys(pg, schema, table, tables):
    from psycopg import sql
    groups = {}
    for row in table['foreign_keys']:
        groups.setdefault(row[0], []).append(row)
    actions = {'NO ACTION', 'RESTRICT', 'CASCADE', 'SET NULL', 'SET DEFAULT'}
    by_name = {t['name']: t for t in tables}
    for rows in groups.values():
        rows.sort(key=lambda r: r[1])
        parent = rows[0][2]
        if parent not in by_name:
            raise ValueError('Cizí klíč odkazuje na tabulku mimo převod.')
        targets = [r[4] for r in rows]
        if any(t is None for t in targets):
            targets = [c['name'] for c in sorted(by_name[parent]['columns'], key=lambda c: c['pk']) if c['pk']]
        if len(targets) != len(rows):
            raise ValueError('Nejednoznačný složený cizí klíč.')
        update, delete = rows[0][5:7]
        if update not in actions or delete not in actions:
            raise ValueError('Nepodporované pravidlo cizího klíče.')
        pg.execute(sql.SQL('ALTER TABLE {} ADD FOREIGN KEY ({}) REFERENCES {} ({}) ON UPDATE {} ON DELETE {}').format(
            _qualified(schema, table['name']), sql.SQL(',').join(sql.Identifier(r[3]) for r in rows),
            _qualified(schema, parent), sql.SQL(',').join(map(sql.Identifier, targets)),
            sql.SQL(update), sql.SQL(delete)))


def migrate(snapshot_path, profile, schema):
    from psycopg import sql
    schema_name(schema)
    with closing(readonly(snapshot_path)) as src:
        src.execute('BEGIN')  # Pin one source snapshot throughout verification.
        plan = inventory(src)
        # Validate all values before the first target mutation.
        for table in plan['tables']:
            table['content'] = content_digest(src.execute(f'SELECT * FROM {quote(table["name"])}'), table['columns'])
        with profile.connect() as pg, pg.transaction():
            pg.execute('SELECT pg_advisory_xact_lock(hashtextextended(%s, 0))', ('TURTO pilot ' + schema,))
            if pg.execute('SELECT 1 FROM pg_namespace WHERE nspname=%s', (schema,)).fetchone():
                raise ValueError('Cílové schéma již existuje. Vyberte nový název; žádná data se nepřepisují.')
            pg.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(schema)))
            pg.execute(sql.SQL('REVOKE ALL ON SCHEMA {} FROM PUBLIC').format(sql.Identifier(schema)))
            for table in plan['tables']:
                pg.execute(_table_sql(schema, table))
                names = sql.SQL(',').join(sql.Identifier(c['name']) for c in table['columns'])
                with pg.cursor().copy(sql.SQL('COPY {} ({}) FROM STDIN').format(_qualified(schema, table['name']), names)) as copy:
                    for row in src.execute(f'SELECT * FROM {quote(table["name"])}'):
                        copy.write_row(row)
                with pg.cursor(name='verify_' + str(plan['tables'].index(table))) as cursor:
                    cursor.execute(sql.SQL('SELECT {} FROM {}').format(names, _qualified(schema, table['name'])))
                    actual = content_digest(cursor, table['columns'])
                if actual != table['content']:
                    raise ValueError(f'Obsah tabulky {table["name"]} se neshoduje; celý převod se vrací zpět.')
                if table['identity']:
                    maximum = pg.execute(sql.SQL('SELECT MAX({}) FROM {}').format(
                        sql.Identifier(table['identity']), _qualified(schema, table['name']))).fetchone()[0]
                    high = max(maximum or 0, table['sequence'] or 0, 0)
                    sequence = pg.execute('SELECT pg_get_serial_sequence(%s,%s)',
                                          (quote(schema) + '.' + quote(table['name']), table['identity'])).fetchone()[0]
                    pg.execute('SELECT setval(%s,%s,%s)', (sequence, max(high, 1), high > 0))
            # Adding constraints AFTER every table has loaded supports cycles and
            # validates all rows without ever disabling PostgreSQL integrity.
            for table in plan['tables']:
                _foreign_keys(pg, schema, table, plan['tables'])
            manifest = {'format': PILOT_FORMAT, 'schema': schema,
                        'created_at': datetime.now(timezone.utc).isoformat(),
                        'status': 'verified_data_rehearsal', **plan}
            pg.execute(sql.SQL('CREATE TABLE {} (id integer PRIMARY KEY CHECK (id=1), manifest jsonb NOT NULL)').format(
                _qualified(schema, '_turto_pilot_manifest')))
            pg.execute(sql.SQL('INSERT INTO {} VALUES (1,%s::jsonb)').format(_qualified(schema, '_turto_pilot_manifest')),
                       (json.dumps(manifest, ensure_ascii=False),))
            # No GUI activation/configuration writes, implicit retry or local fallback.
        return manifest


def verify(profile, schema):
    """Recheck committed data in one repeatable-read transaction."""
    from psycopg import sql
    schema_name(schema)
    with profile.connect() as pg, pg.transaction():
        pg.execute('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY')
        manifest = pg.execute(sql.SQL('SELECT manifest FROM {} WHERE id=1').format(
            _qualified(schema, '_turto_pilot_manifest'))).fetchone()[0]
        if manifest.get('format') != PILOT_FORMAT or manifest.get('application_ready') is not False:
            raise ValueError('Neočekávaný formát pilotní databáze.')
        results = []
        for table in manifest['tables']:
            names = sql.SQL(',').join(sql.Identifier(c['name']) for c in table['columns'])
            with pg.cursor(name='verify_' + str(len(results))) as cursor:
                cursor.execute(sql.SQL('SELECT {} FROM {}').format(names, _qualified(schema, table['name'])))
                actual = content_digest(cursor, table['columns'])
            results.append({'table': table['name'], 'ok': actual == table['content'], **actual})
        return {'schema': schema, 'ok': all(r['ok'] for r in results), 'tables': results, 'application_ready': False}
