#!/usr/bin/env python3
"""Apply the non-workflow source integration for TURTO CRM 7.0.0."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()


def read(rel: str) -> str:
    return (ROOT / rel).read_text(encoding="utf-8")


def write(rel: str, text: str) -> None:
    (ROOT / rel).write_text(text, encoding="utf-8")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


# Harden the new layout owner: settings are stable across version-number changes
# and do not depend on a particular UNIQUE declaration in older databases.
path = "ZakazkyApp_base_6.1/v700_ux.py"
text = read(path)
text = replace_once(
    text,
    "    import json\n    import threading\n",
    "    import json\n    import re\n    import threading\n",
    "v700 imports",
)
text = replace_once(
    text,
    '''        except Exception:\n            title = "TURTO"\n        columns = tree_columns(tree)\n''',
    '''        except Exception:\n            title = "TURTO"\n        title = re.sub(r"\\d+(?:\\.\\d+)+", "", title).strip() or "TURTO"\n        columns = tree_columns(tree)\n''',
    "stable tree title",
)
text = replace_once(
    text,
    '''            with M.db() as con:\n                con.execute(\n                    """INSERT INTO user_settings(user_name,key,value) VALUES(?,?,?)\n                       ON CONFLICT(user_name,key) DO UPDATE SET value=excluded.value""",\n                    (user, key, json.dumps(state, ensure_ascii=False)),\n                )\n''',
    '''            with M.db() as con:\n                con.execute(\n                    "DELETE FROM user_settings WHERE user_name=? AND key=?",\n                    (user, key),\n                )\n                con.execute(\n                    "INSERT INTO user_settings(user_name,key,value) VALUES(?,?,?)",\n                    (user, key, json.dumps(state, ensure_ascii=False)),\n                )\n''',
    "layout setting upsert",
)
write(path, text)


# Development launcher mirrors the production launcher generated by publish-update.sh.
write(
    "ZakazkyApp_base_6.1/ZakazkyCRM.pyw",
    '''import app,crm_features,crm_runtime,crm_v605,crm_price_lists,v606_features,v608_stability,v611_audit,v613_ui,v614_next,v615_input,v616_stability,v617_offerhub,v618_inputfix,v619_fixes,v620_outlookdrop,v621_prices,v623_exports,v624_legacy_exports,v625_stability,v628_modernui_resize,v631_diskdrop,v632_offerlinks,v633_offerassign_deadlines,v636_action_offers_stabletable,v637_project_offer_model,v638_table_updatefix,v640_warning_cleanup,v644_default_date_sort,post_baseline,v700_ux\ncrm_features.apply(app);crm_runtime.apply(app);crm_v605.apply(app);v606_features.apply(app);v608_stability.apply(app);v611_audit.apply(app);v613_ui.apply(app);v614_next.apply(app);v615_input.apply(app);v616_stability.apply(app);v617_offerhub.apply(app);v618_inputfix.apply(app);v619_fixes.apply(app);v620_outlookdrop.apply(app);v621_prices.apply(app);v623_exports.apply(app);v625_stability.apply(app);v628_modernui_resize.apply(app);v632_offerlinks.apply(app);v633_offerassign_deadlines.apply(app);v636_action_offers_stabletable.apply(app);v637_project_offer_model.apply(app);v638_table_updatefix.apply(app);v640_warning_cleanup.apply(app);post_baseline.apply(app);v631_diskdrop.apply(app);v644_default_date_sort.apply(app);crm_features.install_offer_ui(app);crm_price_lists.apply(app);v700_ux.apply(app)\napp.cleanup_stale_test_session();app.ensure_schema();app.ensure_test_user();app.migrate_v41_visual_once();app.import_mail_contacts_v220_once();app.import_mail_contacts_v221_once();app.restore_people_from_v280_backup_once();app.post_import_cleanup_v222_once();app.App().mainloop()\n''',
)


# Production package composition and release validation.
path = "scripts/publish-update.sh"
text = read(path)
text = replace_once(
    text,
    'python scripts/validate-6339-catalog-price-ux.py "$BASE_DIR"\nrm -rf "$STAGE"\n',
    'python scripts/validate-6339-catalog-price-ux.py "$BASE_DIR"\npython scripts/validate-7000-workflow-table-ux.py "$BASE_DIR"\nrm -rf "$STAGE"\n',
    "pre-stage 7.0 validation",
)
text = replace_once(
    text,
    '''  v638_table_updatefix.py v640_warning_cleanup.py \\\n  v644_default_date_sort.py post_baseline.py\n''',
    '''  v638_table_updatefix.py v640_warning_cleanup.py \\\n  v644_default_date_sort.py v700_ux.py post_baseline.py\n''',
    "runtime move list",
)
text = replace_once(
    text,
    '''import app,crm_features,crm_runtime,crm_v605,crm_price_lists,v606_features,v608_stability,v611_audit,v613_ui,v614_next,v615_input,v616_stability,v617_offerhub,v618_inputfix,v619_fixes,v620_outlookdrop,v621_prices,v623_exports,v624_legacy_exports,v625_stability,v628_modernui_resize,v631_diskdrop,v632_offerlinks,v633_offerassign_deadlines,v636_action_offers_stabletable,v637_project_offer_model,v638_table_updatefix,v640_warning_cleanup,v644_default_date_sort,post_baseline\n''',
    '''import app,crm_features,crm_runtime,crm_v605,crm_price_lists,v606_features,v608_stability,v611_audit,v613_ui,v614_next,v615_input,v616_stability,v617_offerhub,v618_inputfix,v619_fixes,v620_outlookdrop,v621_prices,v623_exports,v624_legacy_exports,v625_stability,v628_modernui_resize,v631_diskdrop,v632_offerlinks,v633_offerassign_deadlines,v636_action_offers_stabletable,v637_project_offer_model,v638_table_updatefix,v640_warning_cleanup,v644_default_date_sort,post_baseline,v700_ux\n''',
    "generated launcher imports",
)
text = replace_once(
    text,
    '''crm_features.apply(app);crm_runtime.apply(app);crm_v605.apply(app);v606_features.apply(app);v608_stability.apply(app);v611_audit.apply(app);v613_ui.apply(app);v614_next.apply(app);v615_input.apply(app);v616_stability.apply(app);v617_offerhub.apply(app);v618_inputfix.apply(app);v619_fixes.apply(app);v620_outlookdrop.apply(app);v621_prices.apply(app);v623_exports.apply(app);v625_stability.apply(app);v628_modernui_resize.apply(app);v632_offerlinks.apply(app);v633_offerassign_deadlines.apply(app);v636_action_offers_stabletable.apply(app);v637_project_offer_model.apply(app);v638_table_updatefix.apply(app);v640_warning_cleanup.apply(app);post_baseline.apply(app);v631_diskdrop.apply(app);v644_default_date_sort.apply(app);crm_features.install_offer_ui(app);crm_price_lists.apply(app)\n''',
    '''crm_features.apply(app);crm_runtime.apply(app);crm_v605.apply(app);v606_features.apply(app);v608_stability.apply(app);v611_audit.apply(app);v613_ui.apply(app);v614_next.apply(app);v615_input.apply(app);v616_stability.apply(app);v617_offerhub.apply(app);v618_inputfix.apply(app);v619_fixes.apply(app);v620_outlookdrop.apply(app);v621_prices.apply(app);v623_exports.apply(app);v625_stability.apply(app);v628_modernui_resize.apply(app);v632_offerlinks.apply(app);v633_offerassign_deadlines.apply(app);v636_action_offers_stabletable.apply(app);v637_project_offer_model.apply(app);v638_table_updatefix.apply(app);v640_warning_cleanup.apply(app);post_baseline.apply(app);v631_diskdrop.apply(app);v644_default_date_sort.apply(app);crm_features.install_offer_ui(app);crm_price_lists.apply(app);v700_ux.apply(app)\n''',
    "generated launcher apply order",
)
text = replace_once(
    text,
    'test -e "$DIR/_runtime/v644_default_date_sort.py"\n',
    'test -e "$DIR/_runtime/v644_default_date_sort.py"\ntest -e "$DIR/_runtime/v700_ux.py"\n',
    "runtime v700 existence",
)
text = replace_once(
    text,
    'grep -q "crm_features.install_offer_ui(app);crm_price_lists.apply(app)" "$DIR/ZakazkyCRM.pyw"\n',
    'grep -q "crm_features.install_offer_ui(app);crm_price_lists.apply(app);v700_ux.apply(app)" "$DIR/ZakazkyCRM.pyw"\ngrep -q "def group_offer_items" "$DIR/_runtime/v700_ux.py"\n',
    "runtime v700 launcher assertion",
)
text = replace_once(
    text,
    '''assert text.index('crm_features.install_offer_ui(app)') < text.index('crm_price_lists.apply(app)')\n''',
    '''assert text.index('crm_features.install_offer_ui(app)') < text.index('crm_price_lists.apply(app)')\nassert text.index('crm_price_lists.apply(app)') < text.index('v700_ux.apply(app)')\n''',
    "runtime v700 order assertion",
)
write(path, text)


# Real-Tk integration test must compose the same final layer.
path = "scripts/validate-real-ui.py"
text = read(path)
text = replace_once(
    text,
    "    import v644_default_date_sort\n    import post_baseline\n",
    "    import v644_default_date_sort\n    import post_baseline\n    import v700_ux\n",
    "real UI v700 import",
)
text = replace_once(
    text,
    "    crm_features.install_offer_ui(app)\n    crm_price_lists.apply(app)\n",
    "    crm_features.install_offer_ui(app)\n    crm_price_lists.apply(app)\n    v700_ux.apply(app)\n",
    "real UI v700 apply",
)
write(path, text)


write("release_version.txt", "7.0.0\n")
write(
    "release_notes.txt",
    """• Dialog Poptávka nyní v části „Podobné předchozí poptávky“ zobrazuje výhradně poptávky patřící ke stejné Akci. Podobnost názvu materiálu už výsledky nerozšiřuje o jiné Akce.\n• Tabulátor v dialogových formulářích přeskakuje pomocná tlačítka jako „+ Nová společnost“, „+ Nová akce“, správce číselníku nebo kalendář. V Poptávce vede pořadí přímo Dodavatel → Odběratel → Akce.\n• Výběr Akce v dialogu Příležitost má stejné rozložení jako výběr Společnosti: našeptávač a tlačítko „+ Nová akce“ jsou v jednom společném řádku a mají sjednocené zarovnání.\n• Šířky sloupců tabulek se ukládají samostatně pro každého uživatele. Po opětovném spuštění se obnoví a poslední viditelný sloupec automaticky vyplní volnou šířku, takže podbarvení řádků pokračuje až k pravému okraji bez bílého pruhu.\n• Cenové tabulky, Ceníky, Přijaté a Vydané nabídky, Katalog produktů a obdobné obchodní přehledy mají po kliknutí pravým tlačítkem na záhlaví volbu „Nastavit zobrazené sloupce…“. Sloupce lze skrývat, znovu zobrazovat a měnit jejich pořadí; nastavení se ukládá pro uživatele.\n• Archivace Poptávek nově zpracuje všechny označené řádky najednou. Před potvrzením zobrazí počet a náhled vybraných záznamů a pro každou poptávku zachová samostatný zápis v historii.\n• Položky Vydané nabídky vždy zobrazují Skupinu a Podskupinu. Produkty stejné podskupiny se v editoru i PDF seskupí pod jediný společný nadpis, i když byly původně vloženy v různých částech seznamu.\n• Název skupiny a podskupiny se ukládá jako cenový snímek řádku Vydané nabídky. Pozdější přejmenování nebo přesun výrobku v Katalogu proto nezmění starší uloženou nabídku ani její PDF revizi.\n• Databázová změna je pouze aditivní. Existující Poptávky, Ceníky, Přijaté nabídky, Vydané nabídky, PDF revize, archivy i uživatelská data zůstávají zachovány.\n""",
)

print("Applied TURTO CRM 7.0.0 source integration")
