#!/usr/bin/env python3
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = ROOT / "ZakazkyApp_base_6.1"


def sub_once(text, pattern, replacement, label, flags=0):
    new, count = re.subn(pattern, replacement, text, count=1, flags=flags)
    if count != 1:
        raise RuntimeError(f"{label}: expected one replacement, got {count}")
    return new


def replace_once(text, old, new, label):
    if old not in text:
        raise RuntimeError(f"{label}: source block not found")
    return text.replace(old, new, 1)


# ---------------------------------------------------------------------------
# Nevoga provider: preserve red at span level and change Excel to 4+2 layout.
# ---------------------------------------------------------------------------
provider_path = BASE / "offers_engine" / "providers" / "nevegar.py"
text = provider_path.read_text(encoding="utf-8")

text = sub_once(
    text,
    r"def _band_value\(row_spans, name\):\n.*?\n\n\ndef _red_notes",
    '''def _band_segments(row_spans, name):
    x0, x1 = _BANDS[name]
    selected = [
        span for span in row_spans
        if x0 <= (span["x0"] + span["x1"]) / 2 < x1
    ]
    return [
        {"text": _clean(span.get("text") or ""), "red": bool(span.get("red"))}
        for span in selected
        if _clean(span.get("text") or "")
    ]


def _band_value(row_spans, name):
    selected = _band_segments(row_spans, name)
    return (
        _clean(" ".join(span["text"] for span in selected)),
        any(span["red"] for span in selected),
    )


def _red_notes''',
    "provider band fragments",
    flags=re.S,
)

text = sub_once(
    text,
    r"def _technical_description\(values, red_fields, alternative_note=\"\"\):\n.*?\n\n\ndef _price_modifier",
    '''def _technical_description(values, field_segments, alternative_note=""):
    """Build one product description while keeping supplier colour span-exact.

    Prefixes such as ``lü=`` and units such as ``cm`` are generated by TURTO and
    therefore stay black. Only source fragments whose PDF span was actually red
    receive the red format. A legacy set of red field names is still accepted so
    older regression fixtures remain compatible.
    """
    if isinstance(field_segments, set):
        legacy_red = set(field_segments)
        field_segments = {
            key: [{"text": _clean(value), "red": key in legacy_red}]
            for key, value in values.items()
            if _clean(value)
        }

    segments = []

    def push(text, changed=False, bold=False):
        text = str(text or "")
        if not text:
            return
        current = {
            "text": text,
            "bold": bool(bold),
            "color": "#FF0000" if changed else "",
            "changed": bool(changed),
        }
        if (
            segments
            and segments[-1]["bold"] == current["bold"]
            and segments[-1]["color"] == current["color"]
            and segments[-1]["changed"] == current["changed"]
        ):
            segments[-1]["text"] += current["text"]
        else:
            segments.append(current)

    def add_group(parts):
        parts = [part for part in parts if str(part[0] or "")]
        if not parts:
            return
        if segments:
            push(" | ")
        for value, changed, bold in parts:
            push(value, changed=changed, bold=bold)

    def source_parts(field, fallback=""):
        source = list((field_segments or {}).get(field) or [])
        if not source:
            value = _clean(fallback)
            return [(value, False, False)] if value else []
        parts = []
        for index, fragment in enumerate(source):
            value = _clean(fragment.get("text") or "")
            if not value:
                continue
            if parts:
                parts.append((" ", False, False))
            parts.append((value, bool(fragment.get("red")), False))
        return parts

    if alternative_note:
        # The TURTO label itself is not present in the supplier PDF, so it must
        # never be coloured. Only the supplier's original red note is red.
        add_group([
            ("ALTERNATIVA – ", False, True),
            (alternative_note, True, True),
        ])

    version = _clean(values.get("version")).upper()
    family = _VERSION_NAMES.get(version, version or "PLEXUS")
    version_red = any(
        bool(fragment.get("red"))
        for fragment in list((field_segments or {}).get("version") or [])
    )
    add_group([(family, version_red, False)])

    type_code = _clean(values.get("type")).upper()
    if type_code:
        add_group([("typ ", False, False)] + source_parts("type", type_code))

    for key, prefix, suffix in _TECH_FIELDS[2:]:
        value = _clean(values.get(key))
        if not value:
            continue
        add_group(
            [(prefix, False, False)]
            + source_parts(key, value)
            + [(suffix, False, False)]
        )

    plain = "".join(segment["text"] for segment in segments)
    return plain, segments


def _price_modifier''',
    "provider exact rich description",
    flags=re.S,
)

old = '''        values = {}
        red_fields = set()
        for name in _BANDS:
            value, is_red = _band_value(spans, name)
            values[name] = value
            if is_red:
                red_fields.add(name)
        values["item_no"] = item_no
'''
new = '''        values = {}
        field_segments = {}
        red_fields = set()
        for name in _BANDS:
            source_segments = _band_segments(spans, name)
            field_segments[name] = source_segments
            value = _clean(" ".join(segment["text"] for segment in source_segments))
            values[name] = value
            if any(segment["red"] for segment in source_segments):
                red_fields.add(name)
        values["item_no"] = item_no
'''
text = replace_once(text, old, new, "provider row source segments")

text = replace_once(
    text,
    '''        description, rich_segments = _technical_description(
            values,
            red_fields,
            alternative_text if is_alternative else "",
        )
''',
    '''        description, rich_segments = _technical_description(
            values,
            field_segments,
            alternative_text if is_alternative else "",
        )
''',
    "provider description call",
)

text = replace_once(
    text,
    '''                "rich_segments": rich_segments,
                "changed_fields": sorted(red_fields),
                "alternative": is_alternative,
''',
    '''                "rich_segments": rich_segments,
                "changed_fields": sorted(red_fields),
                "changed_fragments": [
                    {"field": field, "text": fragment["text"]}
                    for field, fragments in field_segments.items()
                    for fragment in fragments
                    if fragment.get("red")
                ],
                "plexus_type": type_code,
                "alternative": is_alternative,
''',
    "provider changed fragments and type",
)

text = sub_once(
    text,
    r'''        headers = \("Poz\.", "Kód", "Popis výrobku", "Obrázek", "Množství", "MJ", "Cena/ks", "Celkem"\)\n        start = 8\n.*?        sheet\.freeze_panes\(start \+ 1, 0\)''',
    '''        start = 8
        sheet.write(start, 0, "Poz.", formats["head"])
        sheet.write(start, 1, "Kód", formats["head"])
        sheet.merge_range(start, 2, start, 5, "Popis výrobku", formats["head"])
        sheet.merge_range(start, 6, start, 7, "Obrázek PLEXUS", formats["head"])
        for col, label in (
            (8, "Množství"),
            (9, "MJ"),
            (10, "Cena/ks"),
            (11, "Celkem"),
        ):
            sheet.write(start, col, label, formats["head"])

        for offset, item in enumerate(data.get("items") or [], 1):
            row = start + offset
            sheet.write(row, 0, item.get("position") or offset, formats["cell"])
            sheet.write(row, 1, item.get("product") or "", formats["cell"])

            # Four Excel columns belong to the single Popis výrobku value.
            sheet.merge_range(row, 2, row, 5, "", formats["wrap"])
            _write_rich_description(sheet, row, 2, item, formats)

            # The next two columns are reserved exclusively for the exact shape
            # image selected from the supplier's PLEXUS type catalogue.
            sheet.merge_range(row, 6, row, 7, "", formats["cell"])
            image = item.get("image_bytes")
            if image:
                image_data = io.BytesIO(image)
                sheet.insert_image(
                    row,
                    6,
                    f"plexus-{item.get('plexus_type') or 'type'}.{item.get('image_ext') or 'png'}",
                    {
                        "image_data": image_data,
                        "x_scale": 0.55,
                        "y_scale": 0.55,
                        "x_offset": 7,
                        "y_offset": 4,
                        "object_position": 1,
                    },
                )

            sheet.write_number(row, 8, float(item.get("quantity") or 0), formats["cell"])
            sheet.write(row, 9, item.get("unit") or "ks", formats["cell"])
            sheet.write_number(row, 10, float(item.get("unit_price") or 0), formats["money"])
            sheet.write_number(row, 11, float(item.get("item_total") or 0), formats["money"])
            sheet.set_row(row, 88)

        sheet.set_column("A:A", 7)
        sheet.set_column("B:B", 22)
        sheet.set_column("C:F", 15)
        sheet.set_column("G:H", 12)
        sheet.set_column("I:J", 11)
        sheet.set_column("K:L", 16)
        sheet.freeze_panes(start + 1, 0)''',
    "provider 4+2 Excel layout",
    flags=re.S,
)

provider_path.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# CRM detail: never paint the full row red. Show an exact rich description
# preview instead, so only actual red source fragments are red.
# ---------------------------------------------------------------------------
layer_path = BASE / "v769_nevoga_offer.py"
text = layer_path.read_text(encoding="utf-8")
text = text.replace(
    '"""TURTO CRM 7.6.9 - Nevoga / Reinforcement Systems rich offer descriptions.',
    '"""TURTO CRM 7.6.10 - Nevoga / Reinforcement Systems exact rich descriptions.',
    1,
)

text = sub_once(
    text,
    r'''    for cls in candidates:\n.*?\n    previous_export_offer_excel = getattr\(M, "export_offer_excel", None\)''',
    '''    for cls in candidates:
        if getattr(cls, "_turto_v769_nevoga_detail", False):
            continue
        previous_build = cls._build

        def build(self, *args, __previous=previous_build, **kwargs):
            result = __previous(self, *args, **kwargs)
            try:
                offer = getattr(self, "offer_row", None)
                supplier = (offer["supplier"] if offer is not None else "") or ""
                if not _is_nevoga_name(supplier):
                    return result
                tree = getattr(self, "tree", None)
                if tree is None:
                    return result

                try:
                    tree.heading("Původní název", text="Popis výrobku")
                except Exception:
                    pass

                with M.db() as con:
                    rows = con.execute(
                        "SELECT id,details_rich_json FROM supplier_offer_items "
                        "WHERE offer_id=?",
                        (int(self.oid),),
                    ).fetchall()
                rich_by_iid = {
                    f"i{row['id']}": _decode_segments(row["details_rich_json"])
                    for row in rows
                }

                # Never colour an entire table row merely because one supplier
                # value changed. That would overstate what was red in the PDF.
                for iid in tree.get_children(""):
                    tags = [
                        tag for tag in (tree.item(iid, "tags") or ())
                        if tag != "supplier_changed"
                    ]
                    tree.item(iid, tags=tuple(tags))

                existing_children = list(self.f.winfo_children())
                before_widget = existing_children[-1] if existing_children else None
                preview = M.ttk.Frame(self.f, style="Card.TFrame", padding=8)
                M.ttk.Label(
                    preview,
                    text="Popis výrobku – červeně pouze změna z nabídky výrobce",
                    style="PageSubtitle.TLabel",
                ).pack(anchor="w", pady=(0, 3))
                rich_text = M.tk.Text(
                    preview,
                    height=2,
                    wrap="word",
                    font=("Calibri", 10),
                    borderwidth=0,
                    relief="flat",
                    padx=4,
                    pady=4,
                )
                rich_text.pack(fill="x", expand=True)
                rich_text.tag_configure("normal", font=("Calibri", 10))
                rich_text.tag_configure("bold", font=("Calibri", 10, "bold"))
                rich_text.tag_configure("red", foreground="#C62828", font=("Calibri", 10))
                rich_text.tag_configure(
                    "red_bold", foreground="#C62828", font=("Calibri", 10, "bold")
                )
                rich_text.configure(state="disabled")

                def render_exact_description(_event=None):
                    selection = tuple(tree.selection())
                    iid = selection[0] if selection else ""
                    segments = rich_by_iid.get(iid) or []
                    rich_text.configure(state="normal")
                    rich_text.delete("1.0", "end")
                    for segment in segments:
                        changed = bool(segment.get("changed"))
                        bold = bool(segment.get("bold"))
                        tag = (
                            "red_bold" if changed and bold
                            else "red" if changed
                            else "bold" if bold
                            else "normal"
                        )
                        rich_text.insert("end", segment.get("text") or "", tag)
                    rich_text.configure(state="disabled")

                tree.bind("<<TreeviewSelect>>", render_exact_description, add="+")
                try:
                    if before_widget is not None:
                        preview.pack(fill="x", pady=(6, 0), before=before_widget)
                    else:
                        preview.pack(fill="x", pady=(6, 0))
                except Exception:
                    preview.pack(fill="x", pady=(6, 0))

                selection = tuple(tree.selection())
                if not selection:
                    first = tree.get_children("")
                    if first:
                        tree.selection_set(first[0])
                render_exact_description()
            except Exception:
                pass
            return result

        cls._build = build
        cls._turto_v769_nevoga_detail = True

    previous_export_offer_excel = getattr(M, "export_offer_excel", None)''',
    "CRM exact rich preview",
    flags=re.S,
)

text = replace_once(
    text,
    '''        "excel_partial_red": True,
        "detail_changed_rows_red": True,
''',
    '''        "excel_partial_red": True,
        "detail_changed_rows_red": False,
        "detail_exact_rich_preview": True,
        "excel_description_columns": 4,
        "excel_image_columns": 2,
''',
    "CRM 7.6.10 contract",
)
layer_path.write_text(text, encoding="utf-8")


# ---------------------------------------------------------------------------
# Release validation and metadata.
# ---------------------------------------------------------------------------
publish_path = ROOT / "scripts" / "publish-update.sh"
text = publish_path.read_text(encoding="utf-8")
text = replace_once(
    text,
    'python scripts/validate-767-offer-reprocess-images.py "$BASE_DIR"\n',
    'python scripts/validate-767-offer-reprocess-images.py "$BASE_DIR"\n'
    'python scripts/validate-769-nevoga-rich-description.py "$BASE_DIR"\n'
    'python scripts/validate-7610-nevoga-exact-red-excel.py "$BASE_DIR"\n',
    "publish Nevoga validations",
)
publish_path.write_text(text, encoding="utf-8")

workflow_path = ROOT / ".github" / "workflows" / "publish-update.yml"
text = workflow_path.read_text(encoding="utf-8")
text = replace_once(
    text,
    '      - scripts/validate-767-offer-reprocess-images.py\n',
    '      - scripts/validate-767-offer-reprocess-images.py\n'
    '      - scripts/validate-769-nevoga-rich-description.py\n'
    '      - scripts/validate-7610-nevoga-exact-red-excel.py\n'
    '      - ZakazkyApp_base_6.1/v769_nevoga_offer.py\n',
    "publish workflow paths",
)
text = replace_once(
    text,
    '''      - name: Validate identical-offer reprocessing
        shell: bash
        run: python scripts/validate-767-offer-reprocess-images.py ZakazkyApp_base_6.1

      - name: Build, validate and publish
''',
    '''      - name: Validate identical-offer reprocessing
        shell: bash
        run: python scripts/validate-767-offer-reprocess-images.py ZakazkyApp_base_6.1

      - name: Validate Nevoga one-description persistence
        shell: bash
        run: python scripts/validate-769-nevoga-rich-description.py ZakazkyApp_base_6.1

      - name: Validate Nevoga exact red and 4+2 Excel layout
        shell: bash
        run: python scripts/validate-7610-nevoga-exact-red-excel.py ZakazkyApp_base_6.1

      - name: Build, validate and publish
''',
    "publish workflow validation steps",
)
workflow_path.write_text(text, encoding="utf-8")

v760_path = ROOT / "scripts" / "validate-7600-table-activity-performance.py"
text = v760_path.read_text(encoding="utf-8")
text = text.replace('"7.6.8", "7.6.9"}', '"7.6.8", "7.6.9", "7.6.10"}', 1)
v760_path.write_text(text, encoding="utf-8")

v768_path = ROOT / "scripts" / "validate-768-clean-table-markers.py"
text = v768_path.read_text(encoding="utf-8")
text = text.replace('{"7.6.8", "7.6.9"}', '{"7.6.8", "7.6.9", "7.6.10"}', 1)
v768_path.write_text(text, encoding="utf-8")

v769_validation = ROOT / "scripts" / "validate-769-nevoga-rich-description.py"
text = v769_validation.read_text(encoding="utf-8")
text = text.replace(
    'print("OK 7.6.9: one technical description, existing rich JSON keeps supplier red changes, no geometry columns")',
    'print("OK 7.6.9+: one technical description, rich JSON keeps exact supplier red changes, no geometry columns")',
    1,
)
v769_validation.write_text(text, encoding="utf-8")

(ROOT / "release_version.txt").write_text("7.6.10\n", encoding="utf-8")
(ROOT / "release_notes.txt").write_text(
    "• Nevoga / REINFORCEMENT SYSTEMS: červeně se nyní zobrazuje výhradně přesný úsek, který je červený v originální nabídce výrobce. Pokud je například změněna pouze kratší hodnota lü, červená je jen tato hodnota; prefix lü=, jednotky ani zbytek řádku se nebarví.\n"
    "• Detail přijaté nabídky už nebarví celý řádek. Pod tabulkou zobrazuje přesný Popis výrobku s částečným formátováním podle originálu.\n"
    "• Excel extrakce používá pro Popis výrobku přesně čtyři sloupce (C:F). Následující dva sloupce (G:H) jsou vyhrazené konkrétnímu obrázku tvaru podle typu PLEXUS.\n"
    "• Obrázek se nadále vybírá z katalogu tvarů v nabídce podle typu A/C/D/I/J/AA/AC/AD/B/CC/DD/E/F/G/H/K/L/M/O a ukládá se přímo k položce.\n"
    "• Databázový model zůstává jednoduchý: technické hodnoty jsou stále jediný Popis výrobku plus formátovací metadata; nevznikají nové sloupce pro lü, b, h, Ø ani další rozměry.\n",
    encoding="utf-8",
)

print("Patched TURTO CRM 7.6.10")
