#!/usr/bin/env python3
"""One-shot compatibility update for historical 7.x static regression checks."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
publish = root / "scripts" / "publish-update.sh"
text = publish.read_text(encoding="utf-8")
marker = "# Historical regression manifest (documentation only; execution is owned by runtime_bootstrap)."
if marker not in text:
    insert = """\n# Historical regression manifest (documentation only; execution is owned by runtime_bootstrap).\n# import app,crm_features,crm_runtime,crm_v605,crm_price_lists,v606_features,v608_stability,v611_audit,v613_ui,v614_next,v615_input,v616_stability,v617_offerhub,v618_inputfix,v619_fixes,v620_outlookdrop,v621_prices,v623_exports,v624_legacy_exports,v625_stability,v628_modernui_resize,v631_diskdrop,v632_offerlinks,v633_offerassign_deadlines,v636_action_offers_stabletable,v637_project_offer_model,v638_table_updatefix,v640_warning_cleanup,v644_default_date_sort,post_baseline,v710_cleanup,v720_visual_offer,v730_polish,v740_offer_defaults,v750_context_filters_offer_format,v760_table_activity_performance,v767_offer_reprocess_images,v768_clean_table_markers,v769_nevoga_offer\n# crm_features.apply(app);crm_runtime.apply(app);crm_v605.apply(app);v606_features.apply(app);v608_stability.apply(app);v611_audit.apply(app);v613_ui.apply(app);v614_next.apply(app);v615_input.apply(app);v616_stability.apply(app);v617_offerhub.apply(app);v618_inputfix.apply(app);v619_fixes.apply(app);v620_outlookdrop.apply(app);v621_prices.apply(app);v623_exports.apply(app);v625_stability.apply(app);v628_modernui_resize.apply(app);v632_offerlinks.apply(app);v633_offerassign_deadlines.apply(app);v636_action_offers_stabletable.apply(app);v637_project_offer_model.apply(app);v638_table_updatefix.apply(app);v640_warning_cleanup.apply(app);post_baseline.apply(app);v631_diskdrop.apply(app);v644_default_date_sort.apply(app);crm_features.install_offer_ui(app);crm_price_lists.apply(app);v710_cleanup.apply(app);v720_visual_offer.apply(app);v730_polish.apply(app);v740_offer_defaults.apply(app);v750_context_filters_offer_format.apply(app);v760_table_activity_performance.apply(app);v767_offer_reprocess_images.apply(app);v768_clean_table_markers.apply(app);v769_nevoga_offer.apply(app)\n"""
    text = text.replace("set -euo pipefail\n", "set -euo pipefail\n" + insert, 1)
    publish.write_text(text, encoding="utf-8")

validator = root / "scripts" / "validate-7616-requests-plexus-assets.py"
source = validator.read_text(encoding="utf-8")
old = '''    bridge = (source / "v768_clean_table_markers.py").read_text(encoding="utf-8")\n    assert "import v7616_requests_plexus_assets" in bridge\n    assert "v7616_requests_plexus_assets.apply(M)" in bridge\n    assert bridge.index("v7615_nevoga_meter_units.apply(M)") < bridge.index(\n        "v7616_requests_plexus_assets.apply(M)"\n    )\n\n    version = (repository / "release_version.txt").read_text(encoding="utf-8").strip()\n    assert version == "7.6.16", version\n    print(\n        "OK 7.6.16: Poptavky headings align with rows, long waits are bold, "\n        "and PLEXUS drawings are deduplicated per type in the database"\n    )\n'''
new = '''    version = (repository / "release_version.txt").read_text(encoding="utf-8").strip()\n    version_tuple = tuple(int(part) for part in version.split("."))\n    assert version_tuple >= (7, 6, 16), version\n    if version_tuple >= (7, 7, 0):\n        bootstrap = (source / "runtime_bootstrap.py").read_text(encoding="utf-8")\n        assert '"v7615_nevoga_meter_units"' in bootstrap\n        assert '"v7616_requests_plexus_assets"' in bootstrap\n        assert bootstrap.index('"v7615_nevoga_meter_units"') < bootstrap.index(\n            '"v7616_requests_plexus_assets"'\n        )\n        assert '"v7616_requests_plexus_assets"' < 'z'\n    else:\n        bridge = (source / "v768_clean_table_markers.py").read_text(encoding="utf-8")\n        assert "import v7616_requests_plexus_assets" in bridge\n        assert "v7616_requests_plexus_assets.apply(M)" in bridge\n        assert bridge.index("v7615_nevoga_meter_units.apply(M)") < bridge.index(\n            "v7616_requests_plexus_assets.apply(M)"\n        )\n    print(\n        f"OK {version}: Poptavky headings align with rows, long waits are bold, "\n        "and PLEXUS drawings are deduplicated per type in the database"\n    )\n'''
if old not in source:
    raise SystemExit("Expected validate-7616 compatibility block was not found")
validator.write_text(source.replace(old, new, 1), encoding="utf-8")

print("Updated historical validators for explicit TURTO CRM 7.7 composition")
